export const EVENT_ASSIGN_TO_SECTOR = 'EVENT_ASSIGN_TO_SECTOR';
export const EVENT_NEW_SHIP = 'EVENT_NEW_SHIP';
export const EVENT_NEW_SECTOR = 'EVENT_NEW_SECTOR';
export const EVENT_NEW_TIMESTAMP = 'EVENT_NEW_TIMESTAMP';
export const EVENT_MERGE_SECTORS = 'EVENT_MERGE_SECTORS';
export const EVENT_CHANGE_SECTOR = 'EVENT_CHANGE_SECTOR';
export const EVENT_EQUIP_MODIFIER = 'EVENT_EQUIP_MODIFIER';
export const EVENT_START_REFIT = 'EVENT_START_REFIT';
export const EVENT_START_REPAIR = 'EVENT_START_REPAIR';
export const EVENT_FINISH_REFIT = 'EVENT_FINISH_REFIT';
export const EVENT_FINISH_REPAIR = 'EVENT_FINISH_REPAIR';
export const EVENT_DESTROY_SHIP = 'EVENT_DESTROY_SHIP';
export const EVENT_SET_MAP = 'EVENT_SET_MAP';

export const DELETE_EVENT = 'DELETE_EVENT';

export const LOAD_EVENTS = 'LOAD_EVENTS';
